# Numerical python: NumPy

#arrays

In [2]:
import numpy as np 
mylist=[1,2,3]
x=np.array(mylist)
x

array([1, 2, 3])

#pass in a list to create a multidimensional array


In [4]:
m=np.array([[7,8,9],[10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

#use the shape method to find the dimension of the array

In [5]:
m.shape

(2, 3)

In [6]:
x.shape

(3,)

arange returns evenly spaced values within given interval


In [11]:
n=np.arange(0,30,2)
n
#start with zerp, count by 2, end before 30

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

#reshape returns an array with the same data with new shape

In [12]:
n=n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

#linspace returns evenly spaced numbers over a specified interval

In [21]:
o=np.linspace(0,4,9)
o
#returns 9 evenly spaced values between 0 and 4

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [24]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.eye(4)
#returns I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.diag(x)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [34]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [36]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

#combining arrays 

In [38]:
p=np.ones([2,3])
p

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.vstack([p,2*p])
#stack the arrays vertically row-wise

array([[1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [43]:
np.hstack([2*p,p])
#stack the array horizontally

array([[2., 2., 2., 1., 1., 1.],
       [2., 2., 2., 1., 1., 1.]])

#arithmetical operations

In [44]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [47]:
x.dot(y)
#dot product
1*4+2*5+3*6

32

In [51]:
z=np.array([y,y**2])
z
#** is used to take the certain power

array([[ 4,  5,  6],
       [16, 25, 36]])

In [52]:
z.shape

(2, 3)

#use .T to get the transpose

In [50]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [53]:
z.T.shape

(3, 2)

In [54]:
z.dtype
#returns the data type

dtype('int32')

#slicing // indexing

In [56]:
s=np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

#use :to cut a subarray

In [58]:
s[1:5]
#[start:stop]

array([ 1,  4,  9, 16], dtype=int32)

#use negatives to count from back

In [60]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

#second':' is used  to indicate step-size


In [62]:
s[-5::-2]
#here we are starting 5th element from end ,counting backwards by 2 until the bgining

array([64, 36, 16,  4,  0], dtype=int32)

#lets look at multidimensional arrays


In [4]:
r=np.arange(36)
r.resize((6,6))
r


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [5]:
r[2,2]
#use the bracket notation to slice array
##[row,col]

14

#use : to select a range of rows and columns

In [6]:
r[3,3:6]

array([21, 22, 23])

In [7]:
r[:2,:-1]
#all the rows upto(not including)row2 and all the columns upto(not including) the last column

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [9]:
r[-1,::2]
#slice the last row with the interval of 2

array([30, 32, 34])

#conditional indexing

In [10]:
r[r>30]

array([31, 32, 33, 34, 35])

In [12]:
r[r>30]=30
r
#assigning value 30 for the values greater than 30

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

#copying data

#be carefull while copying and modifuing the arrays 

In [13]:
r2=r[:3,:3]
r2
#r2 is a slice of r

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [16]:
r2[:]=0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
r
#r has also been changed

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

#To avoid this, use r.copy to create a copy that will not affect the original array

In [19]:
r3=r.copy()
r3

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [20]:
r3[:]=10

In [21]:
r3
#r3 is modified

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [22]:
r
#r remains unchanged

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])